name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        cd server && npm ci
    
    - name: Build frontend
      run: npm run build
      env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
    
    - name: Build backend
      run: |
        cd server
        npm run build
      env:
        NODE_ENV: production
    
    # Add deployment steps based on your hosting platform
    # Example for AWS:
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1
    #
    # - name: Deploy to AWS
    #   run: |
    #     # Deploy frontend to S3/CloudFront
    #     aws s3 sync dist/ s3://your-bucket-name/
    #     # Deploy backend to ECS/Lambda
    #     aws ecs update-service --cluster your-cluster --service your-service --force-new-deployment 